[DNM] include ceph element in edpm image
openstack-k8s-operators/edpm-image-builder pull request #17
Opened 2023-10-25 06:59 UTC by raukadah

Depends-On: https://github.com/openstack-k8s-operators/edpm-image-builder/pull/16

2023-10-25 09:33 UTC, raukadah commented
Ceph is getting installed in the logs.
https://logserver.rdoproject.org/17/17/caf5cfe58f459c92fe58dd95ae2e9814fff621a1/github-check/eib-content-provider-build-images/72b0ede/ci-framework-data/logs/edpm_images/edpm_hardened_uefi_image_build.log
```
2023-10-25 07:08:44.275 | > ---> Package cephadm.noarch 2:18.2.0-1.el9s will be installed
2023-10-25 07:08:44.275 | > ---> Package openvswitch-selinux-extra-policy.noarch 1.0-31.el9s will be installed
2023-10-25 07:08:44.275 | > ---> Package openvswitch3.1.x86_64 3.1.0-55.el9s will be installed
2023-10-25 07:08:44.275 | > --> Finished dependency resolution
2023-10-25 07:08:44.275 | > Dependencies resolved.
2023-10-25 07:08:44.275 | > ==========================================================================================================================
2023-10-25 07:08:44.275 | >  Package                                    Arch    Version                              Repository                   Size
2023-10-25 07:08:44.275 | > ==========================================================================================================================
2023-10-25 07:08:44.275 | > Installing:
2023-10-25 07:08:44.275 | >  bind-utils                                 x86_64  32:9.16.23-13.el9                    appstream                   200 k
2023-10-25 07:08:44.275 | >  biosdevname                                x86_64  0.7.3-9.el9                          baseos                       36 k
2023-10-25 07:08:44.275 | >  buildah                                    x86_64  1:1.31.3-1.el9                       appstream                   8.6 M
2023-10-25 07:08:44.275 | >  cephadm                                    noarch  2:18.2.0-1.el9s                      centos9-storage             211 k
2023-10-25 07:08:44.275 | >  crudini                                    noarch  0.9.3-4.el9s                         delorean-antelope-testing    25 k
```

2023-10-25 13:06 UTC, steveb requested changes

2023-10-25 13:06 UTC, steveb commented on images/ironic-python-agent-centos-9-stream.yaml
> +  - ceph
No need to add this to the IPA image

2024-06-06 23:21 UTC, steveb commented
Can we close this @raukadah ?

2024-06-24 01:05 UTC, closed without merging