Preparation for Prow CI integration
openstack-k8s-operators/edpm-image-builder pull request #26
Opened 2024-02-29 12:51 UTC by jpodivin

Right now we run only minimal checks on submitted code. By setting basic tests in prow we can make sure to keep certain level of quality and consistency in our code base.

2024-03-01 08:55 UTC, jpodivin commented
recheck
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": true, "msg": "non-zero return code", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "~/src/github.com/openstack-k8s-operators/install_yamls ~/ci-framework-data/artifacts\nbash scripts/gen-namespace.sh\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests ']'\n+ '[' -z openshift-nmstate ']'\n+ OUT_DIR=/home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate ']'\n+ mkdir -p /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate\n+ cat\noc apply -f /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/namespace.yaml\nnamespace/openshift-nmstate created\ntimeout 300s bash -c \"while ! (oc get project openshift-nmstate); do sleep 1; done\"\nNAME                DISPLAY NAME   STATUS\nopenshift-nmstate                  Active\nbash scripts/gen-olm-nmstate.sh\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op ']'\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op ']'\n+ mkdir -p /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr ']'\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr ']'\n+ mkdir -p /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr\n+ echo OPERATOR_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op\nOPERATOR_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op\n+ echo DEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr\nDEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr\n+ cat\n+ cat\n+ cat\noc apply -f /home/zuul/ci-framework-data/artifacts/manifests/openstack-operators/nmstate/op\noperatorgroup.operators.coreos.com/openshift-nmstate-tn6k8 created\nsubscription.operators.coreos.com/kubernetes-nmstate-operator created\ntimeout 300s bash -c \"while ! (oc get deployments/nmstate-operator -n openshift-nmstate); do sleep 10; done\"\nError from server (NotFound): deployments.apps \"nmstate-operator\" not found\nError from server (NotFound): deployments.apps \"nmstate-operator\" not found\nError from server (NotFound): deployments.apps \"nmstate-operator\" not found\nNAME               READY   UP-TO-DATE   AVAILABLE   AGE\nnmstate-operator   0/1     1            0           1s\noc wait deployments/nmstate-operator -n openshift-nmstate --for condition=Available --timeout=300s\ndeployment.apps/nmstate-operator condition met\noc apply -f /home/zuul/ci-framework-data/artifacts/manifests/openshift-nmstate/nmstate/cr\nnmstate.nmstate.io/nmstate created\ntimeout 300s bash -c \"while ! (oc get pod --no-headers=true -l component=kubernetes-nmstate-handler -n openshift-nmstate| grep nmstate-handler); do sleep 10; done\"\nNo resources found in openshift-nmstate namespace.\nnmstate-handler-rc2l5   0/1   Running   0     10s\noc wait pod -n openshift-nmstate -l component=kubernetes-nmstate-handler --for condition=Ready --timeout=300s\npod/nmstate-handler-rc2l5 condition met\ntimeout 300s bash -c \"while ! (oc get deployments/nmstate-webhook -n openshift-nmstate); do sleep 10; done\"\nNAME              READY   UP-TO-DATE   AVAILABLE   AGE\nnmstate-webhook   0/1     1            0           16s\noc wait deployments/nmstate-webhook -n openshift-nmstate --for condition=Available --timeout=300s\ndeployment.apps/nmstate-webhook condition met\nWORKERS='crc-pjmnl-master-0' \\\nbash scripts/gen-nncp.sh\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr ']'\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr ']'\n+ mkdir -p /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr\n+ '[' -z crc-pjmnl-master-0 ']'\n+ '[' -z enp6s0 ']'\n+ '[' -z ospbr ']'\n+ '[' -z 1500 ']'\n+ '[' -z 20 ']'\n+ '[' -z 1 ']'\n+ '[' -n '' ']'\n+ echo DEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr\nDEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr\n+ echo WORKERS crc-pjmnl-master-0\nWORKERS crc-pjmnl-master-0\n+ echo INTERFACE enp6s0\nINTERFACE enp6s0\n+ echo BRIDGE_NAME ospbr\nBRIDGE_NAME ospbr\n+ echo INTERFACE_BGP_1\nINTERFACE_BGP_1\n+ echo INTERFACE_BGP_2\nINTERFACE_BGP_2\n+ echo INTERFACE_MTU 1500\nINTERFACE_MTU 1500\n+ echo VLAN_START 20\nVLAN_START 20\n+ echo VLAN_STEP 1\nVLAN_STEP 1\n+ echo STORAGE_MACVLAN\nSTORAGE_MACVLAN\n+ '[' -n true ']'\n+ echo CTLPLANE_IP_ADDRESS_PREFIX 192.168.122\nCTLPLANE_IP_ADDRESS_PREFIX 192.168.122\n+ echo CTLPLANE_IP_ADDRESS_SUFFIX 10\nCTLPLANE_IP_ADDRESS_SUFFIX 10\n+ echo GATEWAY 192.168.122.1\nGATEWAY 192.168.122.1\n+ echo DNS_SERVER 192.168.122.1\nDNS_SERVER 192.168.122.1\n+ '[' -n '' ']'\n+ '[' -n '' ']'\n+ IP_ADDRESS_SUFFIX=5\n+ IPV6_ADDRESS_SUFFIX=5\n+ rm --force '/home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr/*_nncp.yaml'\n+ for WORKER in ${WORKERS}\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ storage_vlan_id=21\n+ cat\n+ '[' -n '' ']'\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ '[' -n '' ']'\n+ cat\n+ IP_ADDRESS_SUFFIX=6\n+ IPV6_ADDRESS_SUFFIX=6\n+ CTLPLANE_IP_ADDRESS_SUFFIX=11\n+ CTLPLANE_IPV6_ADDRESS_SUFFIX=1\noc apply -f /home/zuul/ci-framework-data/artifacts/manifests/openstack/nncp/cr/\nnodenetworkconfigurationpolicy.nmstate.io/enp6s0-crc-pjmnl-master-0 created\ntimeout 240s bash -c \"while ! (oc wait nncp -l osp/interface=enp6s0 --for jsonpath='{.status.conditions[0].reason}'=SuccessfullyConfigured); do sleep 10; done\"\nnodenetworkconfigurationpolicy.nmstate.io/enp6s0-crc-pjmnl-master-0 condition met\nbash scripts/gen-namespace.sh\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests ']'\n+ '[' -z openstack ']'\n+ OUT_DIR=/home/zuul/ci-framework-data/artifacts/manifests/openstack\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openstack ']'\n+ cat\noc apply -f /home/zuul/ci-framework-data/artifacts/manifests/openstack/namespace.yaml\nnamespace/openstack unchanged\ntimeout 300s bash -c \"while ! (oc get project openstack); do sleep 1; done\"\nNAME        DISPLAY NAME   STATUS\nopenstack                  Active\noc project openstack\nAlready on project \"openstack\" on server \"https://api.crc.testing:6443\".\nbash scripts/gen-netatt.sh\n+ '[' -z /home/zuul/ci-framework-data/artifacts/manifests/openstack/netattach/cr ']'\n+ '[' '!' -d /home/zuul/ci-framework-data/artifacts/manifests/openstack/netattach/cr ']'\n+ mkdir -p /home/zuul/ci-framework-data/artifacts/manifests/openstack/netattach/cr\n+ '[' -z enp6s0 ']'\n+ '[' -z ospbr ']'\n+ '[' -z 20 ']'\n+ '[' -z 1 ']'\n+ '[' -z true ']'\n+ '[' -n true ']'\n+ '[' -n '' ']'\n+ echo DEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack/netattach/cr\nDEPLOY_DIR /home/zuul/ci-framework-data/artifacts/manifests/openstack/netattach/cr\n+ echo INTERFACE enp6s0\nINTERFACE enp6s0\n+ echo VLAN_START 20\nVLAN_START 20\n+ echo VLAN_STEP 1\nVLAN_STEP 1\n+ '[' -n true ']'\n+ echo CTLPLANE_IP_ADDRESS_PREFIX 192.168.122\nCTLPLANE_IP_ADDRESS_PREFIX 192.168.122\n+ echo CTLPLANE_IP_ADDRESS_SUFFIX 10\nCTLPLANE_IP_ADDRESS_SUFFIX 10\n+ '[' -n '' ']'\n+ cat\n+ '[' -n true ']'\n+ cat\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ cat\n+ cat\n+ '[' -n true ']'\n+ cat\n+ cat\n+ cat\n+ '[' -n t [...]

2024-03-12 01:25 UTC, steveb requested changes

2024-03-12 01:25 UTC, steveb commented on OWNERS
> +  - network-approvers
We'll also need a baremetal-approvers

2024-03-12 01:25 UTC, steveb commented on OWNERS_ALIASES
> +aliases:
baremetal-approvers:
  - hjensas
  - juliakreger
  - steveb

2024-03-12 01:25 UTC, steveb commented on OWNERS
> +  - openstack-approvers
- baremetal-approvers

2024-03-13 01:00 UTC, steveb approved these changes

2024-03-13 01:00 UTC, steveb reviewed
/lgtm

2024-03-13 01:01 UTC, merged