Add ironic-python-agent-rhel-9.yaml
openstack-k8s-operators/edpm-image-builder pull request #6
Opened 2023-06-13 07:45 UTC by shreshtha90

This yaml has been tested downstream to build IPA
images on rhel-9.

2023-06-13 14:12 UTC, steveb requested changes

2023-06-13 14:12 UTC, steveb commented on images/ironic-python-agent-rhel-9.yaml
> +  types: [qcow2]
This isn't required

2023-06-13 14:12 UTC, steveb commented on images/ironic-python-agent-rhel-9.yaml
> +  - repo-setup
Could you reorder these and add the comments to align with ironic-python-agent-centos-9-stream.yaml?

2023-06-13 14:12 UTC, steveb commented on images/ironic-python-agent-rhel-9.yaml
> +  min-tmpfs: 7
Could you add these lines?

  debug-trace: 1
  checksum: true

2023-06-13 14:13 UTC, steveb commented
Adding something to the main README.rst for how to build this image would be helpful too

2023-06-14 05:39 UTC, shreshtha90 commented on images/ironic-python-agent-rhel-9.yaml
> +  types: [qcow2]
done

2023-06-20 03:53 UTC, steveb approved these changes
/lgtm

2023-06-20 03:54 UTC, merged